-- Initial schema. This is the SQLite schema this product shipped with, ported
-- to PostgreSQL: integer flags became BOOLEAN, the snapshot blob became BYTEA,
-- and the SQLite-only vacuum bookkeeping table is gone because autovacuum owns
-- reclamation here. Timestamps stay ISO 8601 UTC text, as they were.

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE connections (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    host       TEXT NOT NULL,
    username   TEXT NOT NULL,
    password   TEXT NOT NULL,
    verify_tls BOOLEAN NOT NULL DEFAULT FALSE,
    kind       TEXT NOT NULL DEFAULT 'vcenter',
    created_at TEXT NOT NULL
);

CREATE TABLE schedules (
    connection_id    TEXT PRIMARY KEY REFERENCES connections(id) ON DELETE CASCADE,
    interval_minutes INTEGER NOT NULL DEFAULT 15,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    last_run         TEXT,
    next_run         TEXT,
    last_status      TEXT
);

CREATE TABLE scan_runs (
    id            TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    started       TEXT NOT NULL,
    finished      TEXT,
    status        TEXT NOT NULL,
    error         TEXT,
    snapshot_id   TEXT,
    trigger       TEXT NOT NULL DEFAULT 'manual'
);
CREATE INDEX ix_scan_runs_conn ON scan_runs(connection_id, started);

CREATE TABLE snapshots (
    id             TEXT PRIMARY KEY,
    connection_id  TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    label          TEXT NOT NULL,
    scheduled      BOOLEAN NOT NULL DEFAULT FALSE,
    resource_count INTEGER NOT NULL DEFAULT 0,
    resources_gz   BYTEA
);
CREATE INDEX ix_snapshots_conn ON snapshots(connection_id, created_at);

CREATE TABLE findings (
    snapshot_id TEXT PRIMARY KEY REFERENCES snapshots(id) ON DELETE CASCADE,
    findings    TEXT NOT NULL
);

CREATE TABLE changes (
    id               TEXT PRIMARY KEY,
    connection_id    TEXT NOT NULL,
    from_snapshot_id TEXT NOT NULL,
    to_snapshot_id   TEXT NOT NULL,
    observed_at      TEXT NOT NULL,
    resource_id      TEXT NOT NULL,
    resource_type    TEXT NOT NULL,
    resource_name    TEXT NOT NULL,
    change_type      TEXT NOT NULL,
    significance     TEXT NOT NULL,
    summary          TEXT NOT NULL DEFAULT '',
    property_changes TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX ix_changes_conn_time ON changes(connection_id, observed_at);
CREATE INDEX ix_changes_to_snapshot ON changes(to_snapshot_id);

-- "user" and "time" are quoted everywhere they appear: USER is a reserved word
-- in PostgreSQL and an unquoted one would read as the current_user function.
CREATE TABLE events (
    id            TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    "time"        TEXT NOT NULL,
    source        TEXT NOT NULL DEFAULT 'event',
    type          TEXT NOT NULL,
    category      TEXT NOT NULL DEFAULT 'info',
    message       TEXT NOT NULL DEFAULT '',
    "user"        TEXT,
    resource_id   TEXT,
    resource_name TEXT,
    resource_type TEXT
);
CREATE INDEX ix_events_conn_time ON events(connection_id, "time");
CREATE INDEX ix_events_resource ON events(resource_id, "time");

CREATE TABLE event_capture_state (
    connection_id            TEXT PRIMARY KEY,
    last_complete_end        TEXT,
    task_history_unavailable BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE event_incomplete_intervals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id TEXT NOT NULL,
    since         TEXT NOT NULL,
    until         TEXT NOT NULL,
    attempts      INTEGER NOT NULL DEFAULT 1,
    last_error    TEXT,
    updated_at    TEXT NOT NULL,
    UNIQUE (connection_id, since, until)
);
CREATE INDEX ix_event_incomplete_conn ON event_incomplete_intervals(connection_id, since);
